export const OPERATOR_WAS_SELECTED = 'OPERATOR_WAS_SELECTED';
export const OPERATOR_LIST_WAS_LOADED = 'OPERATOR_LIST_WAS_LOADED';

export const REQUEST_WAS_SENT = 'REQUEST_WAS_SENT';
export const RECIEVE_VALIDATE_STATE = 'RECIEVE_VALIDATE_STATE';