export const OPERATOR_WAS_SELECTED = 'OPERATOR_WAS_SELECTED';
export const OPERATOR_LIST_WAS_LOADED = 'OPERATOR_LIST_WAS_LOADED';

export const REQUEST_WAS_SENT = 'REQUEST_WAS_SENT';
export const RECIEVE_VALIDATE_STATE = 'RECIEVE_VALIDATE_STATE';
export const CHECK_PHONE_VALID = 'CHECK_PHONE_VALID';
export const CHECK_SUM_VALID = 'CHECK_SUM_VALID';


export const POPUP_WAS_OPENED = 'POPUP_WAS_OPENED';
export const POPUP_WAS_CLOSED = 'POPUP_WAS_CLOSED';

